aws:
  endpoint: http://localhost:4566
  dynamodb:
    account-table-name : Account
  secretsmanager:
    #    management api client
  region : ap-southeast-2
  profile: localstack

server:
  port: 8080


management:
  endpoints:
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true
      show-details: always
