aws:
  endpoint: http://localhost:4566
  dynamodb:
    person-table-name : dev-Persons
  secretsmanager:
    #    management api client
  region : ap-southeast-2
  profile: localstack

server:
  port: 8082