name: Main branch
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify application
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run static analysis
        run: make verify

  build:
    runs-on: ubuntu-latest
    name: Build application
    needs:
      - verify
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compile the application classes
        shell: bash
        run: make build

  package:
    runs-on: ubuntu-latest
    name: Package & push application image
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-localstack:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/spring-localstack:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/spring-localstack:buildcache,mode=max

  perf-test:
    runs-on: ubuntu-latest
    name: Run perf tests
    needs:
      - package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Start stack & service
        uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './perf-test/docker-compose.yml'
#      - name: Start service
#        uses: addnab/docker-run-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#          run: |
#            docker run -d -p 8080:8080 --network devstack_backend -e "AWS_ENDPOINT=http://localstack:4566" -e "AWS_ACCESS_KEY_ID=foobar" -e "AWS_SECRET_ACCESS_KEY=foobar" --name=spring-localstack donc83/spring-localstack
#      - name: Check container status
#        shell: bash
#        run: |
#          docker ps
      - name: Execute load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: perf-test/script.js
      - name: Clean up
        shell: base
        run: |
          make devstack.stop
          docker stop spring-localstack
          docker container rm spring-localstack



